### ISSUE TITLE
Swift version not supported

### ISSUE THREAD

**Issue by joshwalker** [loopsocial/firework_ios_sdk#11] opened 2023-02-24 17:49 UTC
I updated to Xcode 14.3beta 1 to see how everything would work and tried to compile.  I'm using Fireworks via SPM.  I got this error message:

`failed to build module 'FireworkVideo'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)', while this compiler is 'Apple Swift version 5.8 (swiftlang-5.8.0.117.11 clang-1403.0.22.8.60)'). Please select a toolchain which matches the SDK.`

This would be avoidable if Library Evolution was enabled `https://www.swift.org/blog/library-evolution/`

**Comment by spookyd** [comment] 2023-02-27 14:49
Hm, interesting because the SDK is built with library evolution enable. This can be confirmed in the `.swiftinterface` as it shows the evolution flag `-enable-library-evolution`. 

![Screen Shot 2023-02-27 at 9 48 27 AM](https://user-images.githubusercontent.com/4504366/221595528-4b949405-6035-4798-a321-97265abe2962.png)

I am able to build with FireworkVideoSDK `v1.6.0` using Xcode `Version 14.1 (14B47b)`. 

The toolchain is `Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)`. While it is not the same version you are having trouble with; `Apple Swift version 5.8 (swiftlang-5.8.0.117.11 clang-1403.0.22.8.60)`. It is different than the version the SDK was built with; `Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)`. 

Given this, I wonder if there is an issue with the Xcode `beta 1` version 🤔. Have you had any other issues with other precompiled SDKs?

**Comment by joshwalker** [comment] 2023-03-07 21:21
I think this is a known issue with Xcode 14.3beta.   https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3-release-notes#Known-Issues

`The Xcode “Strict Concurrency Checking” setting is not correctly passed to the compiler. If you set it to “Minimal” (the default), the compiler will still perform “Targeted” checks. (105637789)`
`Workaround: Add -Xfrontend -strict-concurrency=minimal to OTHER_SWIFT_FLAGS under your project’s Build Settings, or add -Xswiftc -strict-concurrency=minimal when running swift build.`

I haven't yet fixed my issue, but this seems to be the cause.

**Comment by spookyd** [comment] 2023-03-07 21:48
This is good to note. Thank you providing this. I am going to close this issue since this is an issue on the Xcode side.

**Closed as completed by spookyd** 2023-03-07 21:48 UTC
